### ISSUE TITLE
Why my commits don't count in my statistics

### ISSUE THREAD

**Issue by bozonhiggsa** [bozonhiggsa/Design_Patterns#1]
Rules say:

Commits

Commits will appear on your contributions graph if they meet all of the following conditions:

    The email address used for the commits is associated with your GitHub account.
    The commits were made in a standalone repository, not a fork.
    The commits were made:
        In the repository's default branch (usually master)
        In the gh-pages branch (for repositories with Project Pages sites)

In addition, at least one of the following must be true:

    You are a collaborator on the repository or are a member of the organization that owns the repository.
    You have forked the repository.
    You have opened a pull request or issue in the repository.
    You have starred the repository.

I made all of these recommendations, but it don't work.

**Comment by alexstormy** [comment]
maybe you must input in commit form the field smth like that:
Author Name <email@mail.com>

**Comment by bozonhiggsa** [comment]
that's right! thank you, Alex!
